"""Add DirectSharedExpense

Revision ID: 460280aa932b
Revises: cbb22f788365
Create Date: 2026-08-26 16:46:06.938907

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '460280aa932b'
down_revision = 'cbb22f788365'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('direct_shared_expenses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('creator_id', sa.Integer(), nullable=False),
    sa.Column('other_user_id', sa.Integer(), nullable=True),
    sa.Column('other_user_email', sa.String(length=120), nullable=False),
    sa.Column('total_amount', sa.Float(), nullable=False),
    sa.Column('creator_percentage', sa.Float(), nullable=False),
    sa.Column('other_percentage', sa.Float(), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['other_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('direct_shared_expenses')
    # ### end Alembic commands ###
