"""Update DirectSharedExpense for friend request workflow

Revision ID: dba61f739c11
Revises: 460280aa932b
Create Date: 2026-08-26 17:04:23.400951

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dba61f739c11'
down_revision = '460280aa932b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('direct_shared_expenses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('decline_reason', sa.String(length=250), nullable=True))
        batch_op.alter_column('other_user_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('direct_shared_expenses', schema=None) as batch_op:
        batch_op.alter_column('other_user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('decline_reason')

    # ### end Alembic commands ###
